### ISSUE TITLE
Error on step 4/5 The system cannot find the path specified. (os error 3)

### ISSUE THREAD

**Issue by MarcGuiselin** [MarcGuiselin/wedge#3]
Reported by @MatthieuAdler

> I'm new to all of this, so I apologize if this is not the right place to ask, but how would I determine which path the installer is referring to when it gives the error message "Error on step 4/5 The system cannot find the path specified. (os error 3)"?

**Comment by MarcGuiselin** [comment]
This might be an issue with the symlink proxy creation in the default edge install directory. @MatthieuAdler have you used a utility that forcefully uninstalls edge or changes it's install directory somehow?

This is the path in question: `C:\Program Files (x86)\Microsoft\Edge\Application\` and it should contain `msedge.exe`

**Comment by MatthieuAdler** [comment]
> This might be an issue with the symlink proxy creation in the default edge install directory. @MatthieuAdler have you used a utility that forcefully uninstalls edge or changes it's install directory somehow?
> 
> This is the path in question: `C:\Program Files (x86)\Microsoft\Edge\Application\` and it should contain `msedge.exe`

That's exactly what it was! I was experimenting with different solutions yesterday, and forgot to change the directory name back. The installation worked now. Thanks so much for your help!

**Comment by MarcGuiselin** [comment]
Good to know! Glad you resolved the issue 😄
