### ISSUE TITLE
Bing images

### ISSUE THREAD

**Issue by 1111Al** [MarcGuiselin/wedge#4]
Im trying this utility, It seems to be working like a charm so far. There is just a small problem, in the start menu search if you click on certain results on the right side of the search window, it opens with bing image instead of google image. I have installed the Crometana Pro too. Anyway I don't have Cortana on my Windows 11 pro.

**Comment by MarcGuiselin** [comment]
This is intended behaviour. If you click on an image link for bing, the only way for you to see that image is to open up the link in bing since there is no compatibility between bing image search and google image search. The link to the image is bing only; there is no google equivalent.

**Comment by 1111Al** [comment]
Ok, thanks for this awesome small application!
