### ISSUE TITLE
Unattended setup?

### ISSUE THREAD

**Issue by eggbean** [MarcGuiselin/wedge#9]
Hi. Glad to find this. I would like to automate its installation but it's not available through winget. Can the installer be used through scripting?

**Comment by MarcGuiselin** [comment]
Yes! It's not documented anywhere, but you can run the installer with the command line argument `-quiet` for a silent install. Also keep in mind the installer needs to be run in an elevated context.

**Comment by eggbean** [comment]
Great, thanks.

**Comment by eggbean** [comment]
Thanks, but is there also a way to stop the Chrometana Pro webpage come up once it's installed?

I've made this powershell that script that gets called from a main setup script:

```
# Installs the wedge redirector for the Chrometana Pro Chrome extension
# https://github.com/MarcGuiselin/wedge
# https://github.com/MarcGuiselin/chrometana-pro
$wedgeDownloadPath = Join-Path $env:TEMP "wedge-download"
if (Test-Path -Path $wedgeDownloadPath) {
    Remove-Item -Path $wedgeDownloadPath -Recurse -Force
}
New-Item -ItemType Directory -Path $wedgeDownloadPath | Out-Null
Set-Location -Path $wedgeDownloadPath
$uri = "https://github.com/MarcGuiselin/wedge/releases/latest/download/installer.exe"
Invoke-WebRequest -Uri $uri -OutFile installer.exe
./installer.exe -quiet
```
The main script gets run every now and again, so while it's not a big problem it's a bit irritating.

Or is there a way of checking if `wedge` is already installed so that the script doesn't run? Having it run seems to be a convenient way to install updates without even thinking about it though.
